# spring-data-mongodb会准备MongoTemplate对象, 提供远程访问操作
spring:
  data:
    mongodb:
      host: 192.168.112.128  # MongoDB主机地址
      port: 27017            # MongoDB端口号
      database: bjsxt        # 访问的数据库database名称
      username: bjsxt        #  登录用户名
      password: bjsxt        #  登录用户密码
      authentication-database: admin  # 认证数据库database名称
